# Generated by Django 5.2.6 on 2025-10-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_advance_payment_markup_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='advance_payment_markup_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='distributorship_markup_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='markup_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='sales_target_markup_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
