# Generated by Django 5.2.6 on 2025-10-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_advance_payment_markup_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tester_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
