# Generated by Django 5.2.6 on 2025-10-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_tester_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
            preserve_default=False,
        ),
    ]
