# Generated by Django 5.2.6 on 2025-10-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date',
            field=models.DateTimeField(default='2025-10-09 15:30:00'),
            preserve_default=False,
        ),
    ]
