# Generated by Django 5.2.6 on 2025-10-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
