# Generated by Django 5.2.6 on 2025-09-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductMaster',
            new_name='Product',
        ),
    ]
